apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-helm-release-prod
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  targetNamespace: production
  releaseName: cnpg-release
  chart:
    spec:
      chart: ./kubernetes/charts/cnpg
      version: '1.0.*'
      valuesFiles:
        - values.yaml
        - values-prod.yaml
      sourceRef:
        kind: GitRepository
        name: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
