apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tm-helm-release-dev
  namespace: flux-system
spec:
  interval: 15m
  timeout: 10m
  targetNamespace: development
  releaseName: tm-release
  dependsOn:
    - name: cnpg-helm-release-dev
      namespace: flux-system
  chart:
    spec:
      chart: ./kubernetes/charts/task-management
      version: '1.0.*'
      valuesFiles:
        - kubernetes/charts/task-management/values.yaml
        - kubernetes/charts/task-management/values-dev.yaml
      sourceRef:
        kind: GitRepository
        name: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled