namespace: development

replicaCount: 1

strategy:
  type: Recreate

ingress:
  ingressClassName: traefik
  rules:
    - host: task-management.dev.local
      http:
        paths:
          - path: /
            backend:
              service:
                name: task-management-service

ASPNETCORE_ENVIRONMENT: Development