labels:
  app: task-management

containers:
  - name: task-management
    repository: sohatz/task-management
    tag: v1.0.1
    pullPolicy: IfNotPresent
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5

ASPNETCORE_ENVIRONMENT: Development