namespace: production

replicaCount: 3

strategy:
  type: RollingUpdate
  maxSurge:
  maxUnavailable: 25%

ingress:
  ingressClassName: traefik
  rules:
    - host: task-management.local
      http:
        paths:
          - path: /
            backend:
              service:
                name: task-management-service

ASPNETCORE_ENVIRONMENT: Production