labels:
  app: task-management

containers:
  - name: task-management
    repository: sohatz/task-management
    tag: v1.0.3
    pullPolicy: Always
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 5
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 5

ASPNETCORE_ENVIRONMENT: Development