apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg-repo
  namespace: flux-system
spec:
  interval: 15m
  url: https://github.com/cloudnative-pg/charts/tree/main/charts/cloudnative-pg