apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-helm-release
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  targetNamespace: cnpg-system
  releaseName: cnpg-release
  chart:
    spec:
      chart: cloudnative-pg
      version: '0.27.*'
      sourceRef:
        kind: HelmRepository
        name: cnpg-repo
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
