apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tm-helm-release-prod
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  targetNamespace: production
  releaseName: tm-release
  chart:
    spec:
      chart: ./kubernetes/charts/task-management
      version: '1.0.*'
      valuesFrom:
      # Values file to merge in,
      # expected to be a relative path in the chart directory
      - chartFileRef:
          path: values.yaml
      - chartFileRef:
          path: values-prod.yaml
      sourceRef:
        kind: GitRepository
        name: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled