apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ default "25%" .Values.strategy.maxSurge }}
      maxUnavailable: {{ default "25%" .Values.strategy.maxUnavailable }}
    {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
      {{- range .Values.containers }}
      - name: {{ .name }}
        image: {{ .repository }}:{{ .tag }}
        pullPolicy: {{ .pullPolicy }}
        ports:
        - containerPort: 8080
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: postgres-db-app
                key: host
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-db-app
                key: dbname
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgres-db-app
                key: port
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-db-app
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-db-app
                key: password
          - name: ASPNETCORE_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: ASPNETCORE_ENVIRONMENT
          - name: ConnectionStrings__TaskManagementConnectionString
            value: {{ include "taskmanagement.connectionString" . }}
        # livenessProbe:
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
        #   periodSeconds: {{ .livenessProbe.periodSeconds }}
        # readinessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8080
        #   initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
        #   periodSeconds: {{ .readinessProbe.periodSeconds }}
      {{- end }}