apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-db
  namespace: {{ .Values.namespace }}
spec:
  instances: {{ .Values.instances }}
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: {{ .Values.size }}
  {{- if eq .Values.namespace "production" }}
  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: required
  {{- end }}